In [2]:

import numpy as np
import pandas as pd
import seaborn as sns
import math
import matplotlib.pyplot as plt
%matplotlib inline
data = pd.read_excel("CTG.xls", 'Raw Data')
data.head(10)

,FileName,Date,SegFile,b,e,LBE,LB,AC,FM,UC,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Variab10.txt,1996-12-01,CTG0001.txt,240.0,357.0,120.0,120.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0
2,Fmcs_1.txt,1996-05-03,CTG0002.txt,5.0,632.0,132.0,132.0,4.0,0.0,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
3,Fmcs_1.txt,1996-05-03,CTG0003.txt,177.0,779.0,133.0,133.0,2.0,0.0,5.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
4,Fmcs_1.txt,1996-05-03,CTG0004.txt,411.0,1192.0,134.0,134.0,2.0,0.0,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
5,Fmcs_1.txt,1996-05-03,CTG0005.txt,533.0,1147.0,132.0,132.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
6,Fmcs_2.txt,1996-05-03,CTG0006.txt,0.0,953.0,134.0,134.0,1.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,3.0
7,Fmcs_2.txt,1996-05-03,CTG0007.txt,240.0,953.0,134.0,134.0,1.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,3.0
8,Hasc_1.txt,1995-02-22,CTG0008.txt,62.0,679.0,122.0,122.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,3.0
9,Hasc_1.txt,1995-02-22,CTG0009.txt,120.0,779.0,122.0,122.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,3.0

In [4]:
print(len(data))

2130

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2130 entries, 0 to 2129
Data columns (total 40 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FileName  2126 non-null   object
 1   Date      2126 non-null   datetime64[ns]
 2   SegFile   2126 non-null   object
 3   b         2126 non-null   float64
 4   e         2126 non-null   float64
 5   LBE       2126 non-null   float64
 6   LB        2126 non-null   float64
 7   AC        2126 non-null   float64
 8   FM        2127 non-null   float64
 9   UC        2127 non-null   float64
 10  ASTV      2127 non-null   float64
 11  MSTV      2127 non-null   float64
 12  ALTV      2127 non-null   float64
 13  MLTV      2127 non-null   float64
 14  DL        2128 non-null   float64
 15  DS        2128 non-null   float64
 16  DP        2128 non-null   float64
 17  DR        2128 non-null   float64
 18  Width     2126 non-null   float64
 19  Min       2126 non-null   float64
 20  Max       2126 non-null   float64
 21  Nmax      2126 non-null   float64
 22  Nzeros    2126 non-null   float64
 23  Mode      2126 non-null   float64
 24  Mean      2126 non-null   float64
 25  Median    2126 non-null   float64
 26  Variance  2126 non-null   float64
 27  Tendency  2126 non-null   float64
 28  A         2126 non-null   float64
 29  B         2126 non-null   float64
 30  C         2126 non-null   float64
 31  D         2126 non-null   float64
 32  E         2126 non-null   float64
 33  AD        2126 non-null   float64
 34  DE        2126 non-null   float64
 35  LD        2126 non-null   float64
 36  FS        2126 non-null   float64
 37  SUSP      2126 non-null   float64
 38  CLASS     2126 non-null   float64
 39  NSP       2126 non-null   float64
dtypes: datetime64[ns](1), float64(37), object(2)
memory usage: 665.8+ KB

In [6]:
data.isnull().sum()

FileName    4
Date        4
SegFile     4
b           4
e           4
LBE         4
LB          4
AC          4
FM          3
UC          3
ASTV        3
MSTV        3
ALTV        3
MLTV        3
DL          2
DS          2
DP          2
DR          2
Width       4
Min         4
Max         4
Nmax        4
Nzeros      4
Mode        4
Mean        4
Median      4
Variance    4
Tendency    4
A           4
B           4
C           4
D           4
E           4
AD          4
DE          4
LD          4
FS          4
SUSP        4
CLASS       4
NSP         4
dtype: int64

In [9]:
tdata = data.drop(columns=['FileName', 'SegFile', 'Date']).dropna()
tdata.isnull().sum()

b           0
e           0
LBE         0
LB          0
AC          0
FM          0
UC          0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
DL          0
DS          0
DP          0
DR          0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [11]:
x = np.array(tdata.iloc[:, 3:])
y = np.array(tdata[['NSP']])

In [12]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
X=preprocessing.StandardScaler().fit(x).transform(x)

In [13]:
logmodel = LogisticRegression()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
logmodel.fit(X_train,y_train)

C:\Users\SANKIRTANA\documents\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
y_pred = logmodel.predict(X_test)
y_pred

array([1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 3., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1.,
       1., 1., 2., 1., 3., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 2., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1.,
       1., 3., 2., 2., 1., 1., 3., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1.,
       1., 3., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 2., 3., 1.,
       2., 1., 1., 1., 1., 1., 1., 2., 1., 2., 3., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 3.,
       1., 2., 3., 1., 1., 1., 1., 1., 1., 3., 3., 1., 3., 1., 2., 3., 1.,
       3., 1., 1., 1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 1., 2., 1., 2.,
       1., 3., 1., 1., 1., 1., 2., 3., 1., 1., 2., 1., 1., 1., 1., 3., 2.,
       1., 1., 2., 3., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       2., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 3., 1., 3.,
       1., 3., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 3., 2.,
       2., 1., 2., 1., 3., 1., 1., 3., 1., 3., 3., 1., 1., 1., 3., 1., 3.,
       1., 2., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 3., 3., 1., 2., 2.,
       1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 3., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 3.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.,
       1.])

In [15]:

mat = confusion_matrix(y_test, y_pred)
mat

array([[326,   0,   0],
       [  1,  57,   0],
       [  0,   0,  42]], dtype=int64)

In [16]:
logmodel.score(X_test,y_test)

0.9976525821596244